### PR TITLE
Android update with KeyMint

### PR DESCRIPTION
**Pull request by primetomas**

### CODE REVIEW

**Comment by primetomas** [comment]
@vanbroup I removed <br> from the Android section in this PR. Is that the best formatting we can achieve?

**Comment by vanbroup** [comment]
Maybe we don't need to show the full link?
```md
[DeviceCheck (developer.apple.com)](https://developer.apple.com/documentation/devicecheck<br/>https://developer.apple.com/documentation/devicecheck/dcappattestservice/3573911-attestkey), [link 2](...) 
```

**Comment by primetomas** [comment]
I don't really understand the request, but I moved out the Android info to a separate section which works well imho. If we have such sections it's easy to add more details information.

**Comment by vanbroup** [comment]
Thanks, this is much better. I will create an issue for the request, we can discuss that separately.

**Comment by primetomas** [comment]
Great. If you merge this I can do the same for the Apple entry.

**Pull request merged**
